import React from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { signOut, useSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export default function Layout({ children }: { children: JSX.Element }) {
  const session = useSession();

  return (
    <>
      <Head>
        <title>TRIVIA APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/quiz.png" />
      </Head>
      {session.status === "authenticated" && (
        <header className="flex justify-around items-center">
          <h1 className="text-center text-2xl lg:text-4xl font-black py-4 tracking-widest">
            TRIVIA QUIZ
          </h1>
          <button
            className="text-white"
            onClick={() => signOut({ redirect: false })}
          >
            Sign Out
          </button>
        </header>
      )}
      <main className={`${inter.className} my-8`}>{children}</main>;
    </>
  );
}
